version: "3"

services:
  broker:
    image: eclipse-mosquitto
    container_name: broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  listener:
    build: .
    container_name: listener
    depends_on:
      - broker
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DOCKER_LISTENER_ORG: espws
      DOCKER_LISTENER_TOKEN: ${INFLUX_TOKEN}
      DOCKER_LISTENER_BUCKET: db0
      DOCKER_LISTENER_BROKER_URL: ${BROKER_URL}
    command: python listener.py
  db:
    image: influxdb
    container_name: influx
    ports:
      - 8086:8086
    volumes:
      - influx-storage:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: espws
      DOCKER_INFLUXDB_INIT_BUCKET: db0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
  api:
    build: .
    container_name: api
    ports:
      - 8000:8000
    command: uvicorn --host 0.0.0.0 api:app
    environment:
      DOCKER_API_ORG: espws
      DOCKER_API_TOKEN: ${INFLUX_TOKEN}


volumes:
  influx-storage:
