version: "3"

services:
  broker:
    image: eclipse-mosquitto
    container_name: broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  listener:
    build: .
    container_name: listener
    depends_on:
      - broker
    environment:
      PYTHONUNBUFFERED: 1
